### ISSUE TITLE
Failing to create folder

### ISSUE THREAD

**Issue by jonasraoni** [bsobbe/iThenticate#10]
Hi @bsobbe!

I'll come back soon with a PR to update the reference URL (the linked reference is outdated) and also fix the issue I had when creating a folder.

**Comment by jonasraoni** [comment]
https://github.com/bsobbe/iThenticate/pull/11

**Comment by bsobbe** [comment]
thanks for your contribution. [#11](https://github.com/bsobbe/iThenticate/pull/11) merged!
